Start to add tests for CLI.

diff --git a/data/cli/cli.sh.erb b/data/cli/cli.sh.erb
--- a/data/cli/cli.sh.erb
+++ b/data/cli/cli.sh.erb
@@ -3,47 +3,78 @@
 
 set -e
 
-EXECUTABLE=$(basename $0)
+APP_NAME=$(basename $0)
+# useful for testing
+ROOT_PATH=${ROOT_PATH:="/"}
 
-function usage {
+_usage() {
   echo "Usage:"
-  echo "  $EXECUTABLE run COMMAND [options]"
-  echo "  $EXECUTABLE scale TYPE=NUM"
-  echo "  $EXECUTABLE config:get VAR"
-  echo "  $EXECUTABLE config:set VAR=VALUE"
-  exit 1
+  echo "  $APP_NAME run COMMAND [options]"
+  echo "  $APP_NAME scale TYPE=NUM"
+  echo "  $APP_NAME logs [--tail]"
+  echo "  $APP_NAME config:get VAR"
+  echo "  $APP_NAME config:set VAR=VALUE"
+}
+
+_realpath() {
+  echo "${ROOT_PATH%%/}${1}"
+}
+
+# Returns the type of process manager supported by the current distribution.
+runner() {
+  if [ -f /etc/debian_version ]; then
+    case "$(cat /etc/debian_version)" in
+      wheezy*|squeeze*)
+        echo "upstart"
+        ;;
+      *)
+        echo "sysv"
+        ;;
+    esac
+  elif [ -f /etc/redhat-release ]; then
+    echo "upstart"
+  else
+    echo "Can't find a runner for your app"
+    exit 1
+  fi
 }
 
 if [ ! 0 -eq ${EUID} ]; then
-  echo "You must be executing with root privileges to launch commands. Either log in as root, use sudo, or add sudo privileges for running ${EXECUTABLE} with your user."
+  echo "You must be executing with root privileges to launch commands."
+  echo "Either log in as root, use sudo, or add sudo privileges for running ${APP_NAME} with your user."
   exit 1
 fi
 
-DEFAULT_FILE=/etc/default/<%= name %>
+DEFAULT_FILE=$(_realpath "/etc/default/${APP_NAME}")
 
 # Source all environment variables for the app. This must be done as
 # privileged user since the config variables are only readable by root.
 . ${DEFAULT_FILE}
 
-# Returns the type of process manager supported by the current distribution.
-function process_manager() {
-  version=$(cat /etc/debian_version)
+for file in $(_realpath "/etc/${APP_NAME}/conf.d")/*; do
+  if [ -f $file ]; then . $file; fi
+done
 
-  case "$version" in
-    wheezy*|squeeze*)
-      init_system="upstart"
-      ;;
-    *)
-      init_system="sysv"
-      ;;
-  esac
-
-  echo "${init_system}"
-}
+for file in $(_realpath "${HOME}/.profile.d")/*.sh; do
+  if [ -f $file ]; then . $file; fi
+done
 
 # You can force a specific process manager by setting the PROCESS_MANAGER
 # environment variable.
-PROCESS_MANAGER=${PROCESS_MANAGER:=$(process_manager)}
+PROCESS_MANAGER=${PROCESS_MANAGER:=$(runner)}
+
+# Return all the environment variables accessible to the app.
+show_env() {
+  env -i ROOT_PATH=${ROOT_PATH} ${0} run env | sort
+}
+
+logs() {
+  cat $(_realpath "/var/log/${APP_NAME}")/*.log | tail -n 100
+}
+
+tail_logs() {
+  tail -f $(_realpath "/var/log/${APP_NAME}")/*.log
+}
 
 function current_number_of_processes() {
   PROCESS_NAME="$1"
@@ -159,10 +190,6 @@ function scale() {
   fi
 }
 
-# Return all the environment variables accessible to the app.
-function show_env() {
-  env -i ${0} run env | sort
-}
 
 while : ; do
   case "$1" in
@@ -171,9 +198,9 @@ while : ; do
       COMMAND="$2"
       shift 2
 
-      runnable=$(echo -n "cd ${HOME} && exec")
+      runnable=$(echo -n "cd $(_realpath ${HOME}) && exec")
 
-      if [ -f "${HOME}/vendor/pkgr/processes/${COMMAND}" ]; then
+      if [ -f $(_realpath "${HOME}/vendor/pkgr/processes/${COMMAND}") ]; then
         # Command alias defined in Procfile
         runnable="${runnable}$(printf " %q" "vendor/pkgr/processes/${COMMAND}" "$@")"
       else
@@ -188,14 +215,14 @@ while : ; do
       # Do not use su, to avoid creating a new process. Note: chroot version
       # is too old on Ubuntu Lucid, so this will fail. It works on Debian
       # Squeeze though (and later).
-      exec chroot --userspec ${APP_USER}:${APP_GROUP} / sh -c "$runnable"
+      exec chroot --userspec ${APP_USER}:${APP_GROUP} "/" sh -c "$runnable"
 
       break ;;
 
     scale)
       shift
       for arg in "$@"; do
-        [ "$arg" = "" ] && usage
+        [ "$arg" = "" ] && _usage
 
         process=(${arg//=/ })
         process_name=${process[0]}
@@ -205,33 +232,43 @@ while : ; do
       done
       break ;;
 
+    logs)
+      shift
+      if [ "$1" = "--tail" ]; then
+        tail_logs
+      else
+        logs
+      fi
+      break;;
+
     config)
       show_env
       break;;
 
     config:set)
-      [ $# -lt 2 ] && usage
+      [ $# -lt 2 ] && _usage
 
       CONFIG=(${2//=/ })
 
       VAR=${CONFIG[0]:?"Invalid variable name"}
       VALUE=${CONFIG[1]:?"Invalid value"}
 
-      DEFAULT_CONF_FILE="/etc/${APP_NAME}/conf.d/other"
+      CONFIG_FILE=$(_realpath "/etc/${APP_NAME}/conf.d/other")
+      touch ${CONFIG_FILE}
 
-      sed -i -r "s/^.*${VAR}.*$//g" /etc/${APP_NAME}/conf.d/*
+      sed -i -r "s/^.*${VAR}.*$//g" $(_realpath "/etc/${APP_NAME}/conf.d")/*
 
-      echo "export ${VAR}=${VALUE}" >> "${DEFAULT_CONF_FILE}"
+      echo "export ${VAR}=${VALUE}" >> "${CONFIG_FILE}"
 
       break;;
 
     config:get)
-      [ $# -lt 2 ] && usage
+      [ $# -lt 2 ] && _usage
       show_env | grep -e "^${2}=" | sed -r "s/^${2}=//"
       break;;
 
     *)
-      usage
+      _usage
       break ;;
   esac
 done
